development:  
  host: pesto.library.northwestern.edu
  port: 389
  username: cn=Manager,dc=library,dc=northwestern,dc=edu
  password: abba
  group_base: ou=groups,dc=library,dc=northwestern,dc=edu
  base: ou=people,dc=northwestern,dc=edu
  uid: uid
test:  
  host: pesto.library.northwestern.edu
  port: 389
  username: cn=Manager,dc=library,dc=northwestern,dc=edu
  password: abba
  group_base: ou=groups,dc=library,dc=northwestern,dc=edu
  base: ou=people,dc=northwestern,dc=edu
  uid: uid
production:  
  host: ec2-107-20-53-121.compute-1.amazonaws.com
  port: 389
  username: cn=admin,dc=example,dc=com
  password: <%= ENV['LDAP_PASSWORD'] %>
  group_base: ou=Groups,dc=library,dc=northwestern,dc=edu
  base: dc=northwestern,dc=edu
  uid: uid

