development:  
  host: ec2-107-20-53-121.compute-1.amazonaws.com
  port: 389
  username: cn=admin,dc=example,dc=com
  password: simple77
test:  
  host: ec2-107-20-53-121.compute-1.amazonaws.com
  port: 389
  username: cn=admin,dc=example,dc=com
  password: simple77
production:  
  host: ec2-107-20-53-121.compute-1.amazonaws.com
  port: 389
  username: cn=admin,dc=example,dc=com
  password: simple77

